repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Common check for 2026
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      # This lints and fixes common errors (like unused imports)
      - id: ruff
        args: [ --fix ]
      # This handles all your code formatting
      - id: ruff-format
